### ISSUE TITLE
Create a new page listing all the dimensions and metrics available when building Custom Reports 

### ISSUE THREAD

**Issue by mattab** [matomo-org/developer-documentation#227]
It would be valuable to have a page listing all the dimensions, and metrics, that are available and can be used when creating custom reports. The list is available via the APIs `CustomReports.getAvailableMetrics` and `CustomReports.getAvailableDimensions`.

Similarly to how our other dynamic pages are created (such as the API reference: https://developer.piwik.org/api-reference/reporting-api or the [segmentation reference](https://developer.matomo.org/api-reference/reporting-api-segmentation)) the list would be generated by a Matomo instance which has all premium plugins enabled.

We have generated the list manually as of today and here it is:

### Dimensions

    Actions In Visit
    Browser
    Browser Engine
    Browser Version
    Campaign Id
    Content
    Days Since First Visit
    Days Since Last Ecommerce Order
    Device Brand
    Device Model
    Device Type
    Events
    Keyword
    Local Time - Hour (Start Of Visit)
    Local Time - Minute (Start Of Visit)
    Campaign Medium
    Campaign Name
    Number Of Interactions
    Number Of Internal Searches
    Number Of Visits
    Operating System Family
    Resolution
    Server Time - Date (End Of Visit)
    Server Time - Day Of Month (End Of Visit)
    Server Time - Day Of Week (End Of Visit)
    Server Time - Day Of Year (End Of Visit)
    Server Time - Hour (End Of Visit)
    Server Time - Hour (Start Of Visit)
    Server Time - Minute (End Of Visit)
    Server Time - Minute (Start Of Visit)
    Server Time - Month (End Of Visit)
    Server Time - Quarter (End Of Visit)
    Server Time - Second (End Of Visit)
    Server Time - Week Of Year (End Of Visit)
    Server Time - Year (End Of Visit)
    Source
    User ID
    User Type
    Visit Converted A Specific Goal Id
    Visit Converted At Least One Goal
    Visit Duration (in Seconds)
    Visit Ecommerce Status At The End Of The Visit
    Visit Type
    Visitor IP
    Visits By Days Since Last Visit
    City
    Continent
    Country
    Language
    Provider
    Custom Variable Value 1 (scope Conversion)
    Custom Variable Value 1 (scope Page)
    Custom Variable Value 1 (scope Visit)
    Custom Variable Value 2 (scope Conversion)
    Custom Variable Value 2 (scope Page)
    Custom Variable Value 2 (scope Visit)
    Custom Variable Value 3 (scope Conversion)
    Custom Variable Value 3 (scope Page)
    Custom Variable Value 3 (scope Visit)
    Custom Variable Value 4 (scope Conversion)
    Custom Variable Value 4 (scope Page)
    Custom Variable Value 4 (scope Visit)
    Custom Variable Value 5 (scope Conversion)
    Custom Variable Value 5 (scope Page)
    Custom Variable Value 5 (scope Visit)
    Category (Site Search)
    Clicked URL
    Content Interaction
    Content Name
    Content Piece
    Content Target
    Diving Rating
    Download URL
    Entry Page Title
    Entry Page URL
    Exit Page Title
    Exit Page URL
    Interaction Position
    Keyword (Site Search)
    Location
    Page Generation Time
    Page Title
    Page Type
    Page URL
    Server Time - Hour
    Server Time - Minute
    Event Action
    Event Category
    Event Name
    Event URL
    Event Value
    Keyword
    Referrer Name
    Referrer Type
    Referrer URL
    Discount
    Number Of Items In Cart
    Order Value
    Product Name
    Product Price
    Product Quantity
    Product SKU
    Shipping
    Subtotal
    Tax
    Overall Revenue
    Grouped Resource
    Hour
    Impressions
    Media Length (in Seconds)
    Media Progress
    Media Title
    Player Name
    Resolution
    Resource
    Time Spent Playing Media (in Seconds)
    Time To Initial Media Play (in Seconds)
    Form Conversions
    Form Starts
    Form Submissions
    Form Views
    Hesitation Time
    Time Spent
    Time To First Submit

### Metrics

    Avg. Actions In Visit Per Visit
    Avg. Days Since First Visit Per Visit
    Avg. Days Since Last Ecommerce Order Per Visit
    Avg. Events Per Visit
    Avg. Number Of Interactions Per Visit
    Avg. Number Of Internal Searches Per Visit
    Avg. Visit Duration (in Seconds) Per Visit
    Avg. Visits By Days Since Last Visit Per Visit
    Bounce Rate
    Bounces
    Conversion Rate
    Max Actions In Visit
    Max Days Since First Visit
    Max Days Since Last Ecommerce Order
    Max Events
    Max Number Of Interactions
    Max Number Of Internal Searches
    Max Visit Duration (in Seconds)
    Max Visits By Days Since Last Visit
    Total Actions In Visit
    Total Days Since First Visit
    Total Days Since Last Ecommerce Order
    Total Events
    Total Number Of Interactions
    Total Number Of Internal Searches
    Total Visit Duration (in Seconds)
    Total Visits By Days Since Last Visit
    Unique Browser Engines
    Unique Browser Versions
    Unique Browsers
    Unique Campaign Id
    Unique Content
    Unique Device Brands
    Unique Device Models
    Unique Device Types
    Unique Keyword
    Unique Medium
    Unique Name
    Unique Operating System Versions
    Unique Operating Systems
    Unique Resolutions
    Unique Source
    Unique User IDs
    Unique User Type
    Unique Visit Ecommerce Status At The End Of The Visit
    Unique Visit Types
    Unique Visitor IPs
    Unique Visitors
    Visits
    Visits With Conversions
    Unique Cities
    Unique Continents
    Unique Countries
    Unique Languages
    Unique Latitudes
    Unique Longitudes
    Unique Providers
    Unique Regions
    Unique Custom Variable Value 1 (scope Conversion)
    Unique Custom Variable Value 1 (scope Page)
    Unique Custom Variable Value 1 (scope Visit)
    Unique Custom Variable Value 2 (scope Conversion)
    Unique Custom Variable Value 2 (scope Page)
    Unique Custom Variable Value 2 (scope Visit)
    Unique Custom Variable Value 3 (scope Conversion)
    Unique Custom Variable Value 3 (scope Page)
    Unique Custom Variable Value 3 (scope Visit)
    Unique Custom Variable Value 4 (scope Conversion)
    Unique Custom Variable Value 4 (scope Page)
    Unique Custom Variable Value 4 (scope Visit)
    Unique Custom Variable Value 5 (scope Conversion)
    Unique Custom Variable Value 5 (scope Page)
    Unique Custom Variable Value 5 (scope Visit)
    Avg. Generation Time
    Hits
    Max Interaction Position
    Max Page Generation Time
    Pageviews
    Pageviews With Generation Time
    Total Interaction Position
    Total Page Generation Time
    Unique Clicked URLs
    Unique Content Interactions
    Unique Content Names
    Unique Content Pieces
    Unique Content Targets
    Unique Diving Rating
    Unique Download URLs
    Unique Entry Page Titles
    Unique Entry Page URLs
    Unique Exit Page Titles
    Unique Exit Page URLs
    Unique Keywords (Site Search)
    Unique Location
    Average Value
    Events With A Value
    Max Event Value
    Min Event Value
    Total Event Value
    Unique Event Actions
    Unique Event Categories
    Unique Event Names
    Unique Event URLs
    Unique Keywords
    Unique Referrer Names
    Unique Referrer Types
    Unique Referrer URLs
    Avg. Discount Per Order
    Avg. Number Of Items In Cart Per Order
    Avg. Order Value Per Order
    Avg. Shipping Per Order
    Avg. Subtotal Per Order
    Avg. Tax Per Order
    Max Discount
    Max Number Of Items In Cart
    Max Order Value
    Max Product Price
    Max Product Quantity
    Max Shipping
    Max Subtotal
    Max Tax
    Total Discount
    Total Number Of Items In Cart
    Total Order Value
    Total Product Price
    Total Product Quantity
    Total Shipping
    Total Subtotal
    Total Tax
    Unique Orders
    Unique Product Names
    Unique Product SKUs
    Max Overall Revenue
    Total Overall Revenue
    Avg. Completion
    Avg. Media Length
    Avg. Time Spent
    Finish Rate
    Finishes
    Impressions
    Impressions By Unique Visitors
    Max Media Length (in Seconds)
    Max Time Spent Playing Media (in Seconds)
    Max Time To Initial Media Play (in Seconds)
    Play Rate
    Plays
    Total Media Length (in Seconds)
    Total Time Spent Playing Media (in Seconds)
    Total Time To Initial Media Play (in Seconds)
    Unique Grouped Resources
    Unique Media Titles
    Unique Player Names
    Unique Resources
    Unique Video Resolutions
    Form Avg. Hesitation Time
    Form Avg. Time Spent
    Form Avg. Time To First Submit
    Form Conversion Rate
    Form Conversions
    Form Re-submitter Rate
    Form Re-submitters
    Form Starters
    Form Starters Rate
    Form Starts
    Form Submissions
    Form Submitters
    Form Viewers
    Form Views
    Hesitation Time
    Max Form Views
    Max Hesitation Time
    Max Time Spent
    Max Time To First Submit
    Time Spent
    Time To First Submit

**Comment by diosmosis** [comment]
@mattab couple questions:

1. what information would be useful to display w/ dimensions & metrics? Just names? Descriptions too? (note: dimensions don't have descriptions.)
2. should we ignore these dimensions in the doc output: https://github.com/innocraft/plugin-CustomReports/blob/880dc081d0c1133dbef23262f4b275f2f45f3289/API.php#L356
3. I believe some metrics aren't returned by the customreports output. Should these appear in the documentation output?

**Comment by mattab** [comment]
1) let's display name, and description when available. 
1b) for dimensions, is it maybe possible to display the list of all the reports that use this dimension? this could give some context, considering we don't have a description yet
2) let's hide those dimensions
3) what metrics are they? Likely they can be hidden in the doc output..

**Comment by diosmosis** [comment]
1b) Not sure, but will see
3) the logic for skipping metrics isn't super clear, eg, here some processed metrics are skipped: https://github.com/innocraft/plugin-CustomReports/blob/880dc081d0c1133dbef23262f4b275f2f45f3289/API.php#L452, metrics that don't have getQuery() metrics don't exist: https://github.com/innocraft/plugin-CustomReports/blob/880dc081d0c1133dbef23262f4b275f2f45f3289/API.php#L463, etc.

If we're skipping the same stuff CustomReports is skipping, then maybe this is documentation specific to CustomReports? I wonder if developer.matomo.org is the best place for it. Or maybe we can add a field to the output that says "supported by CustomReports" or something. What do you think?

**Comment by mattab** [comment]
indeed this documentation is quite related to Custom Reports at the moment, so maybe it could be a new page "Dimensions & Metrics" under a new Custom Reports category in https://developer.matomo.org/integration ? (we should then also add a new FAQ linking to this page, and link to this new page from the user guide.).

**Comment by mattab** [comment]
This will be available in the glossary after the next release & deploy of Custom Reports plugin (still pending)
