### ISSUE TITLE
[Question] A/B Testing Assign the same user, the same variation

### ISSUE THREAD

**Issue by skube** [matomo-org/developer-documentation#242]
Are users given random variation each time they visit? Or is it possible -- given a [User ID](https://matomo.org/docs/user-id/) is setup -- to give the same user, the same variation each time?

**Comment by tsteur** [comment]
Users are given a random variation first time they enter an A/B test and the same variation will be used for all subsequent visits. I hope this answers your question.

**Comment by skube** [comment]
Also [on the FAQ](https://matomo.org/faq/ab-testing/faq_22509/)
