### ISSUE TITLE
How to add new Measurables using API

### ISSUE THREAD

**Issue by nitishxp** [matomo-org/developer-documentation#295]
Hi All,
Is there any way to add website using API as it is a cumbersome process to add website manually to matomo dashboard.

**Comment by tsteur** [comment]
You can use the API see [SitesManager.addSite](https://developer.matomo.org/api-reference/reporting-api#SitesManager) API method. For all other questions please ask in the forum in the development category: https://forum.matomo.org/c/plugins-platform
