### ISSUE TITLE
wrong JS tracking code

### ISSUE THREAD

**Issue by nicolas-roche** [matomo-org/developer-documentation#303]
Hello,

I cannot figure why matomo gives me a wrong URL (using matomo.php instead of piwik.php) into the Javascript tracker it provides to me (via the IHM and the web service).

This append on upgraded VM (from piwik) on both 3.8.1 and 3.9.1 versions.
On a new 3.9.1 instance, I get the same error from the IHM but I get a correct JS from web services.

Could you help me, I guess I miss something in the configuration ?
Thanks.
```
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//matomo-test.example.org/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '27']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

**Comment by Findus23** [comment]
Hi,

There is nothing wrong with using matomo.php.

It is now recommended by default, but you can still continue to use piwik.php.

**Comment by nicolas-roche** [comment]
Hi Findus, 
thanks you for your quick reply.

Could you advice me how to install the corresponding matomo.php file on server ?
In fact, it does not appear into the debian package we get from debian.matomo.org.

**Comment by Findus23** [comment]
Hi,

You are right, there seems to be a bug in the debian packages where those two files are missing.

I'll report it to the maintainer.
In the meantime you can copy piwik.js to matomo.js and put the following in matomo.php:
```php
<?php
/**
 * Matomo - free/libre analytics platform
 *
 * @link https://matomo.org
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 *
 * @package Piwik
 */

if (!defined('PIWIK_DOCUMENT_ROOT')) {
    define('PIWIK_DOCUMENT_ROOT', dirname(__FILE__) == '/' ? '' : dirname(__FILE__));
}

include PIWIK_DOCUMENT_ROOT . '/piwik.php';
```

**Comment by nicolas-roche** [comment]
Many thanks !
