### ISSUE TITLE
Piwik->Matomo replacement breaks code in docs

### ISSUE THREAD

**Issue by Findus23** [matomo-org/developer-documentation#315]
Reported in https://forum.matomo.org/t/matomo-namespace-in-documentation-it-work/35024

https://github.com/matomo-org/developer-documentation/blob/29048156d60e856e4c63ab224db8199e5bbb68f8/docs/3.x/extending-database.md#adding-new-tables 
gets replaced to 
```php
use Matomo\Db;
use Matomo\Common;
use \Exception;
```

which doesn't work.

**Comment by tsteur** [comment]
Shows correct now on https://developer.matomo.org/guides/extending-database
