### ISSUE TITLE
Change the video title on the fly

### ISSUE THREAD

**Issue by chema2708** [matomo-org/developer-documentation#335]
Hello. I am currently implementing the Media Analytics audio/video for my company's website. I am facing a problem that i cannot solve with the current information that is available from the matomo website.

I have a large video (10:00 min) which is divided by chapters, every chapter has a different duration and each page just seeks to the next chapter. The video source is one and you only load it from the first load. I am using jwplayer.

When i see the visitor's log i see the actions of the player (play, pause, resume, seek) with the video title that i am sending but the main problem is that i want to send a different video title upon changing the screen (i have a non browser refreshing navigation process).

The main reason for this is that i want to keep separated video analytics for each section.

I have tried to dynamically change the data-matomo-title attribute and rescanning for media but does not get reflected in the log.

I hope you can help me.

Thank you

**Comment by tsteur** [comment]
@chema2708 could you email our support about this? The email is shop at innocraft.com

In case you are using a playlist I think this should be in theory supported out of the box and we would be picking up the new name automatically. Changing the video title during the same video is not supported yet. 

> with the video title that i am sending but the main problem is that i want to send a different video title upon changing the screen (i have a non browser refreshing navigation process).

Be great to include in the support email a bit more information around this what you are trying to achieve and what insights you are trying to get out of it. Maybe there are some other ways we can recommend that we already support.
