### ISSUE TITLE
Write a guide how to provide Updates

### ISSUE THREAD

**Issue by tsteur** [matomo-org/developer-documentation#84]
This is kinda crucial for "Extending the database" as at some point there will be updates needed.

For a beginning we could just add a section about Updates to the "Extending the database" guide explaining they can create an update via `./console generate:update`. We could close this ticket after this is done.

In the next step we maybe need a separate guide for this. We will probably write a blog post about this anyway, afterwards we can merge the blog post to a guide.

**Comment by justinvelluppillai** [comment]
Maybe this one can be closed now if I'm not mistaken @tsteur ? This page seems to cover updates, including `generate:update` command https://developer.matomo.org/guides/extending-database

**Comment by tsteur** [comment]
👍
